### ISSUE TITLE
Node JS Version

### ISSUE THREAD

**Issue by hrueger** [Envek/obs-studio-node-example#1]
Hi,
great job!
What version of NodeJS are you using? I always get an error that it requires another node version and that I should try and recompile.

Thanks!

**Comment by emptycrown** [comment]
Hello! Did you make sure to set your Electron version to 6.1.9?

**Comment by hrueger** [comment]
Oops, I realized that this specific version was set in the `package.json`, but I used my global electron installation. Sorry! I'll try again and reopen this issue if necessary.

**Comment by Envek** [comment]
Yes, obs-studio-node currently works only for Electron 6.x. I've tried to build it against electron 7 and 8 but got a lot of C++-level compilation errors due to changes in nodejs APIs.

Upstream issue for reference: https://github.com/stream-labs/obs-studio-node/issues/605 (you are authored it btw :smile:)
